-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.NAME
FROM 
(
SELECT I.ANIMAL_ID, I.NAME, O.DATETIME - I.DATETIME
FROM ANIMAL_INS I RIGHT JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY 3 DESC
) A
LIMIT 2
