-- 코드를 입력하세요
SELECT I.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, 
ADDRESS, ROUND(AVG(REVIEW_SCORE), 2)
FROM REST_INFO I INNER JOIN REST_REVIEW R
ON I.REST_ID = R.REST_ID
WHERE ADDRESS LIKE "서울%"
GROUP BY 1
ORDER BY 6 DESC, 4 DESC