SELECT P.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT) * PRICE
FROM FOOD_PRODUCT P RIGHT JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE PRODUCE_DATE LIKE "2022-05-%"
GROUP BY P.PRODUCT_ID
ORDER BY 3 DESC , 1
