-- 코드를 작성해주세요
WITH MAX_TABLE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) YEAR,
        MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT YEAR, MAX_SIZE - SIZE_OF_COLONY YEAR_DEV, ID
FROM ECOLI_DATA A
INNER JOIN MAX_TABLE B
ON YEAR(DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV